datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/skoczkowie
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql:   true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect 
