
---
server:
  port: 8080
  contextPath: /SpringBootAgJs
---
 
spring:
  profiles: local
datasource:
  appconf:
    url: jdbc:mysql://localhost:3306/skoczkowie
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect 

